name: Jonts Ferreira
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7078965809196234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4c3b71'
    - '#dc2328'
    - '#ffffff'
    - '#f2b9a5'
  brandStrength: 0.4107092823833227
  lightness: 0.020194570533931255
  saturation: 0
  rhythmicContrast: 1
purpose: []
